---
title: "Variables"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## CMS

The CMS Office of Minority Health has designed the Mapping Medicare Disparities Tool (MMD), to identify areas of disparities between subgroups of Medicare beneficiaries (e.g., racial and ethnic groups) in health outcomes, utilization, and spending. From the CMS MMD, we obtained the following attributes at the county level: 

-	Overall and composite PQI (Prevention quality Index) developed by the Agency for Healthcare Research and Quality as a measure of outpatient care quality
-	All-cause hospitalizations
-	All-cause readmissions
-	All-emergency visits


## AHRF

The Health Resources and Services Administration (HRSA) is an agency of the Department of Health and Human Service (DHHS) whose primary goal is to provide health care to people who are geographically isolated, economically or medically vulnerable. From the HRSA data warehouse, we obtained the Area Health Resources Files (AHRF) which include data on health care professions at the county, state and national levels from over 50 data sources. Specifically, we obtained the following attributes at the county level: raw clinician rate and clinician rate per 100,000 people at the state and county level.

## Definitive Healthcare

Last updated Sept. 14th, 2020 

-	Total number of ICU beds
-	Number of pediatric ICU beds
-	Number of adult ICU beds 
-	Number of licensed beds 
-	Number of staffed beds 
-	Hospital type:
  - Short Term Acute Care Hospital
  - Long Term Acute Care Hospital
  - Critical Access Hospital
  - Psychiatric Hospital
  - Rehabilitation Hospital
  - VA hospital
  - Children’s hospital
  - Department of Defense Hospital
  - Religious Non-Medical Health Care Institution

##  County Health Rankings

The County Health Rankings & Roadmaps program is a collaboration between the Robert Wood Johnson Foundation and the University of Wisconsin Population Health Institute. At the county level, we’ve obtained the following attributes from their county health rankings model and data aggregated from governmental resources: 

